platform: support macOS and newer CPython
mandiant/Ghidrathon pull request #4
Opened 2022-08-29 16:44 UTC by shizmob

This PR fixes `util/configure_jep_native_libraries.py` to use the `importlib.metadata` and `pkg_resources` modules if available, before falling back to the old `sys.path` search. It also adds a fallback in case `(lib)jep.*` can't be found, trying again and interposing the implementation cache tag. Native libraries on macOS have been known to use this filename format (e.g.: `jep.cpython-310-darwin.so`). It then changes GhidrathonInterpreter to search for `jep.so` as well.

With this, I was able to get Ghidrathon to work under macOS with `gradle -PGHIDRA_INSTALL_DIR=/usr/local/Caskroom/ghidra/10.1.4-20220519/ghidra_10.1.4_PUBLIC -PPYTHON_BIN=python3 buildExtension`.

2022-09-16 21:04 UTC, mike-hunhoff requested changes
@Shizmob this is great work! Very excited about adding MacOS to the list of supported operating systems. I've left one small comment for your review.

2022-09-16 21:04 UTC, mike-hunhoff commented on util/configure_jep_native_binaries.py
> +        ghidra_os_lib_path = Path(GHIDRA_OS_LIB_PATH) / (GHIDRA_OS_LIB_NAMES[sys.platform] + os.uname().machine)
`os.uname` does not work on Windows - Ghidra only supports 64-bit so we can be confident using hard-coded paths for the `os` directory e.g. `win_x86_64`. We could include the hard-coded paths for each supported OS in `GHIDRA_OS_LIB_NAMES`.

2022-09-16 21:14 UTC, mike-hunhoff commented
> In general though, it would be better if the build process didn't pollute my global Python environment, so it's probably worth making sure that part is run in a virtualenv, or something. Also, instead of cherry-picking files from the Jep site-packages directory, why not copy it over wholesale under the arch-specific Ghidra directory and add it to the Python interpreter path?

Thank you for the feedback! We haven't found a straightforward way to run Jep with Ghidra that doesn't require including the targeted Jep Java and native binaries in specific folders of the extension directory. We could copy everything over but I'm not sure what that gains us - we would still need to cherry-pick the Jep Java binary over to the extension's `lib` directory. It may be worth investigating the pip `--target` switch to install Jep directly to the Ghidrathon extension folder and then configure things from there. I'll open a new issue highlighting these ideas.

2022-09-16 22:00 UTC, mike-hunhoff commented on util/configure_jep_native_binaries.py
> +        ghidra_os_lib_path = Path(GHIDRA_OS_LIB_PATH) / (GHIDRA_OS_LIB_NAMES[sys.platform] + os.uname().machine)
True but Ghidra only supports a subset of those architectures: https://github.com/NationalSecurityAgency/ghidra/blob/c51183f1a262c80d45aac48d4f3343c67b6bd41a/GPL/nativePlatforms.gradle#L21-L28. We just need to make sure that the Jep native binaries are copied to the appropriate `os` directory where Ghidra knows to look e.g. `win_x86_x64`.

2023-01-25 03:36 UTC, rchtsang commented
MacOS support would be nice. I did try out @Shizmob's PR but wasn't able to get it working, even with some of the mentioned fixes in this thread.

I'm currently on an M1 Pro (OSX v13.0.1).

Interestingly, I did manage to get Ghidrathon working, but i had to manually finagle some of the library names. i used `libjep.jnilib` during the build instead of `jep.cpython-310-darwin.so`, then renamed it in the `mac_arm_64` folder after extracting the dist result to `jep.dll` and somehow Ghidra was fine with that.

2023-01-30 20:43 UTC, mike-hunhoff commented
@Shizmob checking to see if you are still working this PR? We have more interest coming in for MacOS and ARM support (see #27) and would love to get this PR wrapped up and merged.

2024-01-27 01:15 UTC, mike-hunhoff commented
Thank you for your contribution - this has been superseded by https://github.com/mandiant/Ghidrathon/commit/32f3969e09a5d29197cabbc28d93dc9c572d7e45.

2024-01-27 01:15 UTC, closed without merging